sudo: required
services:
  - docker
language: java
jdk:
  - openjdk8
env:
  global:
    - DOCKER_IMAGE=zigakleine/team-management-service:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
script:
  - mvn clean package -DskipTests
  - docker build -t "$DOCKER_IMAGE" .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"